name: Backend CI

on:
  push:
    branches:
      - main
      - "feature/**"
    paths-ignore:
      - 'README.md'

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build-Backend
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
     DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [22]

    defaults:
      run:
        working-directory: ./apps/backend

    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./apps/backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck
   
      - name: Run ESLint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run unit tests
        run: npm test

      - name: Generate Prisma Client & Build
        run: npm run build

      - name: Run Security Audit
        run: npm audit --audit-level=high
        continue-on-error: true
